# Generated by Django 5.0.6 on 2024-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormContact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('FormContact_phone', models.IntegerField(blank=True, null=True)),
                ('FormContact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('FormContact_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
