# Generated by Django 5.0.6 on 2024-07-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_formcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formcontact',
            old_name='FormContact_email',
            new_name='formContact_email',
        ),
        migrations.RenameField(
            model_name='formcontact',
            old_name='FormContact_name',
            new_name='formContact_name',
        ),
        migrations.RenameField(
            model_name='formcontact',
            old_name='FormContact_phone',
            new_name='formContact_phone',
        ),
        migrations.RenameField(
            model_name='formcontact',
            old_name='FormContact_text',
            new_name='formContact_text',
        ),
    ]
